[turbobase64] Fix library name conflict.
Avoids conflict:

```
error: The following files are already installed in D:/installed/x64-windows and are in conflict with turbobase64:x64-windows
Installed by aklomp-base64:x64-windows:
  debug/lib/base64.lib
  lib/base64.lib
```

Resolved the conflict in favor of aklomp-base64 because:
1. As far as I can tell turbobase64 is the least used base64 in the registry.
2. Turbobase64 doesn't take the CMake package name base64, and this rename is consistent with that name.